### ISSUE TITLE
Interested in a maintainer / collaborator?

### ISSUE THREAD

**Issue by ScriptedAlchemy** [pixeldesu/moduleRaid#1]
Howdy!

I’ve followed your work for a long time, and have built a few proprietary systems like this project. 
I am working on an software architecture which allows for, among many other things, the ability for many builds to act as one. 

I’ve worked and collaborated on and co authored some of the largest contrubutions to React architecture, one of my co-authors actually wrote require.resolveWeak for our work on Universal code. 

I’d like to propose, could you consider adding me as a collaborator to this project? We both seem to be moving toward the same common goal and rather than waste efforts doing almost the same things, let’s combine forces and help balance up the little time we have to contribute to OSS.

This is a project I am highly interested in, and would be rolling it into my other projects as a dependency. Many of these projects have amassed hundreds of thousands of downloads a week. 

We don’t know each other, but I don’t want to write another closed-source solution to a problem that has yet to be solved publicly. I am sure you are proud of your contribution, and should be! 

I’d love nothing more than to help you drive this forwards for the greater good. Modularaid automation is the cornerstone of true micro frontend multi build asset loading and orchestration. 

I want nothing more than to see this project soar to be used by millions and by some of the biggest companies in the world.

Let me know your thoughts, I understand it is a big ask. I’d like the original of the project to get the recognition than a fork of their hard work. I do hope my GitHub profile will reveal that even though we are strangers, I’m a trustworthy source, asking to work on a project that I believe in. 

Great work! On your Webpack 4 update! I wish I could have PRd mine... but I was still in a closed source situation at the time.  

With respect,
Zack

**Comment by ScriptedAlchemy** [comment]
@pixeldesu bumping. :)

**Comment by pixeldesu** [comment]
@ScriptedAlchemy Thanks for your offer, but this project definitely doesn't need another maintainer or collaborator.

It's an extremely low-effort-to-maintain library that only requires adjustments every now and then, and whatever text you copy-pasted and typo'd `moduleRaid` in is far away from the actual use case.

**Comment by ScriptedAlchemy** [comment]
Fair enough, I hear you.

I did not copy paste my issue or message text. I am dyslexic though so it’s undoubtedly got typos (might have been doing this on my phone as well). Anyways besides the point - I know the project is super small and i suppose that I didn’t know the direction your were taking it in. 

Sorry for the misinterpreted message to you. Your project seemd like it was heading that direction, or could easily have been.

I think i forked your project a while back and hacked some crap onto it, but going to delete it and re-fork your latest work. Moduleraid is still the closest thing I’ve found to cracking open webpack and tinkering with its client side function. 

I might be joining the webpack-contrib group which would make this much easier to pull off, but theres some permission issues with slack invites and such.  

I’d never copy paste some message to an author, especially if it were hustling for write access or maintainership. Thats like just disrespectful to the whole open-source community. 

Thanks for giving me more context around the direction you are taking this project. I agree that we have different ideas and are heading in other directions. Thats totally cool and part of the software world. 

My only concern at this point is that you may think i copy pasted some bullshit message to you. That’s not how i roll and i only message authors or projects i have interest in. Each message is typed from scratch and from the heart. I admittedly typed you a long message mostly because i was super excited about the idea that maybe we were heading the same direction. My message was sincere - I’m just dyslexic.
