### ISSUE TITLE
moduleraid breaks when used in a Webpack v5 bundle

### ISSUE THREAD

**Issue by eramdam** [pixeldesu/moduleRaid#5]
What the title says 😅 
For some reaosn the result of `require('moduleraid')` in an app bundled with Webpack v5 is an empty object.

See a repro in this repo https://github.com/eramdam/moduleraid-webpack5-repro

**Comment by ScriptedAlchemy** [comment]
There's significant changes to the runtime. V5 is a lot more robust so you might be able to access this with its api

**Comment by eramdam** [comment]
@ScriptedAlchemy the issue isn't that moduleraid can't access Webpack v5's package at runtime, which I would expect, but rather than _using_ moduleraid **in** a Webpack 5 bundle results in the imported moduleraid code to not work/be an empty object 😅

**Comment by tomer8007** [comment]
See [this issue](https://github.com/pedroslopez/whatsapp-web.js/issues/564), it's fixed in @pedroslopez's fork.

**Comment by eramdam** [comment]
@tomer8007 Hum, it seems like @pedroslopez's fix allows moduleraid to _inspect_ a webpack v5 bundle. My issue happens when _bundling_ moduleraid in a webpack v5 bundle 😅

**Comment by eramdam** [comment]
This was fixed in 5.0.0 🎉
